# ---- sessionservice config ----
spring.datasource.url=jdbc:postgresql://localhost:5432/skillsync_session
spring.datasource.username=postgres
spring.datasource.password=root
jwt.secret=secret123secret123secret123secret123
